# Generated by Django 4.1.7 on 2023-07-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alugueis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='aluguel',
        ),
    ]
