# Generated by Django 4.1.7 on 2023-07-06 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_client_delete_cliente'),
        ('carros', '0003_car_delete_carro'),
        ('alugueis', '0002_rent_delete_aluguel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carros.car'),
        ),
        migrations.AddField(
            model_name='rent',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.client'),
        ),
    ]
