# Generated by Django 4.1.7 on 2023-07-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alugueis', '0002_rent_delete_aluguel'),
        ('usuarios', '0002_remove_cliente_rg_cliente_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('cnh', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='cliente',
        ),
    ]
