# Generated by Django 4.1.7 on 2023-03-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=100)),
                ('ano', models.CharField(max_length=4)),
                ('motor', models.CharField(max_length=20)),
                ('velocidade_maxima', models.CharField(max_length=100)),
                ('tipo_combustivel', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=8)),
                ('numero_chassi', models.CharField(max_length=100)),
                ('capacidade', models.CharField(max_length=100)),
                ('foto', models.FileField(blank=True, upload_to='carros')),
            ],
        ),
    ]
