# Generated by Django 4.1.7 on 2023-07-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alugueis', '0002_rent_delete_aluguel'),
        ('carros', '0002_alter_carro_capacidade_alter_carro_cor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('manufacter', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(max_length=4)),
                ('motor', models.CharField(blank=True, max_length=20, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=100, null=True)),
                ('license_plate', models.CharField(blank=True, max_length=8, null=True)),
                ('photo', models.FileField(blank=True, upload_to='carros')),
            ],
        ),
        migrations.DeleteModel(
            name='carro',
        ),
    ]
