# Generated by Django 4.1.7 on 2023-07-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
